kind: ConfigMap
apiVersion: v1
metadata:
  name: weather-app-config
data:
  config.json: |
    {
      "port": "8080",
      "remote_host": "http://api.weatherstack.com/current?access_key=9a002e43db71f9388084af35b8e4a947&query="
    }